[build]
  command = "npx vite build"
  publish = "dist/public"   # ✅ match the Vite build output

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"